FROM ubuntu:latest

RUN apt-get update && apt-get install -y python3 python3-pip

COPY ./requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

COPY ./app.py /app/app.py

# CMD ["cd", "./app/", "&&", "python3", "-m", "flask", "run", "--host='0.0.0.0'"]

WORKDIR "/app"

CMD ["flask", "run", "--host=0.0.0.0"]

# python -m flask run
